---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  annotations:
    fluxcd.io/tag.podinfod: "semver:*"
    fluxcd.io/locked: "false"
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
      - name: debug
        image: hwchiu/netutils:3.4.5
