apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
    annotations:
      fluxcd.io/automated: "true"
      fluxcd.io/locked: 'false'      
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
      - name: debug
        image: hwchiu/netutils:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
