---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitops-demo
  namespace: default
  annotations:
    tag.fluxcd.io/debug: debug.image.tag
    filter.fluxcd.io/chart-image: "semver:~0.1"
    fluxcd.io/automated: 'true'
spec:
  releaseName: gitops-demo
  chart:
    git: git@github.com:hwchiu/gitops-demo
    path: argocd/
  values:
    image:
      tag: 0.1.4
